/**
 * Assembled App — generated by GitSort (deterministic multi-edge assembler).
 *
 * Walks a path through the Capability Graph and wires 2 capabilities into one
 * instance; a value flows along each seam:
 *   Definitive Self-Contained Camera Capture Component → Photo Download Utility App (saves ImageDataURL to device)
 *
 * Seams (1 wired, avg score 1):
 *   camera-capture-definitive.onCapture → photo-download-app.photo : ImageDataURL
 *
 * Runtime-agnostic; wrap in a project template (web/RN) to build & deploy.
 */
import React, { useState } from 'react';
import DefinitiveCameraCapture from './DefinitiveCameraCapture';
import PhotoDownloaderApp from './PhotoDownloaderApp';

export default function AssembledApp() {
  const [photo, setPhoto] = useState<string>('');

  return (
    <>
      <DefinitiveCameraCapture onCapture={(value) => setPhoto(value)} />
      <PhotoDownloaderApp photo={photo} />
    </>
  );
}
