/**
 * Assembled App — generated by GitSort (deterministic multi-edge assembler).
 *
 * Walks a path through the Capability Graph and wires 3 capabilities into one
 * instance; a value flows along each seam:
 *   Definitive Self-Contained Camera Capture Component → Self-Contained React Image Cropper (react-easy-crop → onCropped) → Photo Download Utility App (saves ImageDataURL to device)
 *
 * Seams (2 wired, avg score 0.975):
 *   camera-capture-definitive.onCapture → react-easy-crop-self-contained.image : ImageDataURL
 *   react-easy-crop-self-contained.onCropped → photo-download-app.photo : ImageDataURL
 *
 * Runtime-agnostic; wrap in a project template (web/RN) to build & deploy.
 */
import React, { useState } from 'react';
import DefinitiveCameraCapture from './DefinitiveCameraCapture';
import ImageCropper from './ImageCropper';
import PhotoDownloaderApp from './PhotoDownloaderApp';

export default function AssembledApp() {
  const [image, setImage] = useState<string>('');
  const [photo, setPhoto] = useState<string>('');

  return (
    <>
      <DefinitiveCameraCapture onCapture={(value) => setImage(value)} />
      <ImageCropper image={image} onCropped={(value) => setPhoto(value)} />
      <PhotoDownloaderApp photo={photo} />
    </>
  );
}
