/**
 * Assembled App — generated by GitSort (deterministic multi-edge assembler).
 *
 * Walks a path through the Capability Graph and wires 2 capabilities into one
 * instance; a value flows along each seam:
 *   Definitive Self-Contained Camera Capture Component → Inspection Report Generator Component
 *
 * Seams (1 wired, avg score 0.95):
 *   camera-capture-definitive.onCapture → new-inspection-report-generator.photoUrl : ImageDataURL
 *
 * Runtime-agnostic; wrap in a project template (web/RN) to build & deploy.
 */
import React, { useState } from 'react';
import DefinitiveCameraCapture from './DefinitiveCameraCapture';
import InspectionReportGenerator from './InspectionReportGenerator';

export default function AssembledApp() {
  const [photoUrl, setPhotoUrl] = useState<string>('');

  return (
    <>
      <DefinitiveCameraCapture onCapture={(value) => setPhotoUrl(value)} />
      <InspectionReportGenerator photoUrl={photoUrl} />
    </>
  );
}
