/**
 * Assembled App — generated by GitSort (deterministic multi-edge assembler).
 *
 * Walks a path through the Capability Graph and wires 2 capabilities into one
 * instance; a value flows along each seam:
 *   React Image Dropzone → onUpload(ImageDataURL) → Photo Download Utility App (saves ImageDataURL to device)
 *
 * Seams (1 wired, avg score 0.95):
 *   image-dropzone-upload.onUpload → photo-download-app.photo : ImageDataURL
 *
 * Runtime-agnostic; wrap in a project template (web/RN) to build & deploy.
 */
import React, { useState } from 'react';
import ImageDropzoneUpload from './ImageDropzoneUpload';
import PhotoDownloaderApp from './PhotoDownloaderApp';

export default function AssembledApp() {
  const [photo, setPhoto] = useState<string>('');

  return (
    <>
      <ImageDropzoneUpload onUpload={(value) => setPhoto(value)} />
      <PhotoDownloaderApp photo={photo} />
    </>
  );
}
