/**
 * Assembled App — generated by GitSort (deterministic multi-edge assembler).
 *
 * Walks a path through the Capability Graph and wires 3 capabilities into one
 * instance; a value flows along each seam:
 *   React Image Dropzone → onUpload(ImageDataURL) → Definitive Self-Contained Camera Capture Component → Photo Download Utility App (saves ImageDataURL to device)
 *
 * Seams (2 wired, avg score 1):
 *   image-dropzone-upload.onUpload → camera-capture-definitive.imageType : ImageDataURL
 *   camera-capture-definitive.onCapture → photo-download-app.photo : ImageDataURL
 *
 * Runtime-agnostic; wrap in a project template (web/RN) to build & deploy.
 */
import React, { useState } from 'react';
import ImageDropzoneUpload from './ImageDropzoneUpload';
import DefinitiveCameraCapture from './DefinitiveCameraCapture';
import PhotoDownloaderApp from './PhotoDownloaderApp';

export default function AssembledApp() {
  const [imageType, setImageType] = useState<string>('');
  const [photo, setPhoto] = useState<string>('');

  return (
    <>
      <ImageDropzoneUpload onUpload={(value) => setImageType(value)} />
      <DefinitiveCameraCapture imageType={imageType} onCapture={(value) => setPhoto(value)} />
      <PhotoDownloaderApp photo={photo} />
    </>
  );
}
