/**
 * Assembled App — generated by GitSort (deterministic multi-edge assembler).
 *
 * Walks a path through the Capability Graph and wires 3 capabilities into one
 * instance; a value flows along each seam:
 *   Image Cropper Component (react-easy-crop) → Definitive Self-Contained Camera Capture Component → Inspection Report Generator Component
 *
 * Seams (2 wired, avg score 0.975):
 *   image-cropper-component-v2.onCropped → camera-capture-definitive.imageType : ImageDataURL
 *   camera-capture-definitive.onCapture → new-inspection-report-generator.photoUrl : ImageDataURL
 *
 * Runtime-agnostic; wrap in a project template (web/RN) to build & deploy.
 */
import React, { useState } from 'react';
import ImageCropper from './ImageCropper';
import DefinitiveCameraCapture from './DefinitiveCameraCapture';
import InspectionReportGenerator from './InspectionReportGenerator';

export default function AssembledApp() {
  const [imageType, setImageType] = useState<string>('');
  const [photoUrl, setPhotoUrl] = useState<string>('');

  return (
    <>
      <ImageCropper onCropped={(value) => setImageType(value)} />
      <DefinitiveCameraCapture imageType={imageType} onCapture={(value) => setPhotoUrl(value)} />
      <InspectionReportGenerator photoUrl={photoUrl} />
    </>
  );
}
