/**
 * Assembled App — generated by GitSort (deterministic multi-edge assembler).
 *
 * Walks a path through the Capability Graph and wires 3 capabilities into one
 * instance; a value flows along each seam:
 *   Definitive Self-Contained Camera Capture Component → Image Cropper Component (react-easy-crop) → Image Editor Component
 *
 * Seams (2 wired, avg score 0.975):
 *   camera-capture-definitive.onCapture → image-cropper-component-v2.image : ImageDataURL
 *   image-cropper-component-v2.onCropped → image-editor-component.image : ImageDataURL
 *
 * Runtime-agnostic; wrap in a project template (web/RN) to build & deploy.
 */
import React, { useState } from 'react';
import DefinitiveCameraCapture from './DefinitiveCameraCapture';
import ImageCropper from './ImageCropper';
import ImageEditor from './ImageEditor';

export default function AssembledApp() {
  const [image, setImage] = useState<string>('');
  const [image2, setImage2] = useState<string>('');

  return (
    <>
      <DefinitiveCameraCapture onCapture={(value) => setImage(value)} />
      <ImageCropper image={image} onCropped={(value) => setImage2(value)} />
      <ImageEditor image={image2} />
    </>
  );
}
