/**
 * Assembly Harness — generated by GitSort (deterministic connector codegen).
 *
 * Wires a proven producer to a proven consumer along a Capability Graph edge:
 *   camera-capture-ultimate-v2 . onCapture : string ‹ImageDataURL› (image/jpeg dataURL)
 *     -> new-inspection-report-generator . photoUrl
 *
 * The seam is one line of glue (the onCapture={…} prop below; matched on canonical ImageDataURL).
 * Drop this screen in alongside the two assets and a ImageDataURL flows end to end.
 */
import React, { useState } from 'react';
import UltimateCameraCapture from '../syntheses/web/cameraCapture/UltimateCameraCaptureComponentV2';
import InspectionReportGenerator from '../components/web/InspectionReportGenerator/index';

export default function UltimateCameraCaptureToInspectionReportGenerator() {
  // The matched value type: string ‹ImageDataURL› (image/jpeg dataURL)
  const [photoUrl, setPhotoUrl] = useState<string>('');

  return (
    <>
      <UltimateCameraCapture onCapture={(value) => setPhotoUrl(value)} />
      <InspectionReportGenerator photoUrl={photoUrl} />
    </>
  );
}
