/**
 * Assembled App — generated by GitSort (deterministic multi-edge assembler).
 *
 * Walks a path through the Capability Graph and wires 3 capabilities into one
 * instance; a value flows along each seam:
 *   Self-Contained React Image Cropper (react-easy-crop → onCropped) → Definitive Self-Contained Camera Capture Component → Photo Download Utility App (saves ImageDataURL to device)
 *
 * Seams (2 wired, avg score 1):
 *   react-easy-crop-self-contained.onCropped → camera-capture-definitive.imageType : ImageDataURL
 *   camera-capture-definitive.onCapture → photo-download-app.photo : ImageDataURL
 *
 * Runtime-agnostic; wrap in a project template (web/RN) to build & deploy.
 */
import React, { useState } from 'react';
import ImageCropper from './ImageCropper';
import DefinitiveCameraCapture from './DefinitiveCameraCapture';
import PhotoDownloaderApp from './PhotoDownloaderApp';

export default function AssembledApp() {
  const [imageType, setImageType] = useState<string>('');
  const [photo, setPhoto] = useState<string>('');

  return (
    <>
      <ImageCropper onCropped={(value) => setImageType(value)} />
      <DefinitiveCameraCapture imageType={imageType} onCapture={(value) => setPhoto(value)} />
      <PhotoDownloaderApp photo={photo} />
    </>
  );
}
