/**
 * Assembled App — generated by GitSort (deterministic multi-edge assembler).
 *
 * Walks a path through the Capability Graph and wires 3 capabilities into one
 * instance; a value flows along each seam:
 *   Photo Download Utility App (saves ImageDataURL to device) → Definitive Self-Contained Camera Capture Component → Inspection Report Generator Component
 *
 * Seams (2 wired, avg score 0.875):
 *   photo-download-app.onDownload → camera-capture-definitive.title : string
 *   camera-capture-definitive.onCapture → new-inspection-report-generator.photoUrl : ImageDataURL
 *
 * Runtime-agnostic; wrap in a project template (web/RN) to build & deploy.
 */
import React, { useState } from 'react';
import PhotoDownloaderApp from './PhotoDownloaderApp';
import DefinitiveCameraCapture from './DefinitiveCameraCapture';
import InspectionReportGenerator from './InspectionReportGenerator';

export default function AssembledApp() {
  const [title, setTitle] = useState<string>('');
  const [photoUrl, setPhotoUrl] = useState<string>('');

  return (
    <>
      <PhotoDownloaderApp onDownload={(value) => setTitle(value)} />
      <DefinitiveCameraCapture title={title} onCapture={(value) => setPhotoUrl(value)} />
      <InspectionReportGenerator photoUrl={photoUrl} />
    </>
  );
}
